#
# Module manifest for the ScoopBucket helper module.
#
# Generated by hand (not via New-ModuleManifest) to keep the file small
# and readable. The companion .psm1 dot-sources Public/, Private/, and
# Classes/ in module scope; ScriptsToProcess also loads Classes\Package.ps1
# into the *caller* scope so bundle scripts can write `[Package]@{ ... }`
# after a plain Import-Module without `using module`.
#
@{
    RootModule        = 'ScoopBucket.psm1'
    ModuleVersion     = '0.2.0'
    GUID              = 'b7e8a4c2-9f3d-4b76-8e6a-1c5d2f7b9e10'
    Author            = 'Mark Michaelis'
    CompanyName       = 'IntelliTect'
    Copyright         = '(c) Mark Michaelis. All rights reserved.'
    Description       = 'Declarative package manifests, install dispatcher, and tab-completion verification for the MarkMichaelis Scoop bucket. Provides the [Package] class, Invoke-PackageInstall, and the cross-bundle Install-Package / Get-Package helpers (which deliberately shadow the rarely-used PackageManagement cmdlets of the same name).'
    PowerShellVersion = '7.0'

    ScriptsToProcess  = @('Classes\Package.ps1')

    FunctionsToExport = @(
        'Install-Package',
        'Get-Package',
        'Invoke-PackageInstall'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()

    PrivateData = @{
        PSData = @{
            Tags         = @('Scoop', 'Winget', 'Chocolatey', 'PackageManagement', 'Install')
            LicenseUri   = 'https://github.com/MarkMichaelis/ScoopBucket/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/MarkMichaelis/ScoopBucket'
            ReleaseNotes = '0.2.0 — Driver pipeline: Invoke-PackageInstall with winget/scoop/choco/npmGlobal/dotnetTool engine dispatchers, AlreadyInstalled probes, PostInstallScript, completion registration (native/pscompletions/auto), end-to-end completion verification via [CommandCompletion]::CompleteInput. Cross-bundle Install-Package and Get-Package helpers (auto-discover migrated bundles).'
        }
    }
}
