#
# Module manifest for the ScoopBucket helper module.
#
# Generated by hand (not via New-ModuleManifest) to keep the file small
# and readable. The companion .psm1 dot-sources Public/, Private/, and
# Classes/ in module scope; ScriptsToProcess also loads Classes\Package.ps1
# into the *caller* scope so bundle scripts can write `[Package]@{ ... }`
# after a plain Import-Module without `using module`.
#
@{
    RootModule        = 'ScoopBucket.psm1'
    ModuleVersion     = '0.3.0'
    GUID              = 'b7e8a4c2-9f3d-4b76-8e6a-1c5d2f7b9e10'
    Author            = 'Mark Michaelis'
    CompanyName       = 'IntelliTect'
    Copyright         = '(c) Mark Michaelis. All rights reserved.'
    Description       = 'Declarative package manifests, install dispatcher, and tab-completion verification for the MarkMichaelis Scoop bucket. Provides the [Package] class, Invoke-PackageInstall, and the cross-bundle Install-Package / Get-Package helpers (which deliberately shadow the rarely-used PackageManagement cmdlets of the same name).'
    PowerShellVersion = '7.0'

    ScriptsToProcess  = @('Classes\Package.ps1')

    FunctionsToExport = @(
        'Install-Package',
        'Get-Package',
        'Invoke-PackageInstall',
        'Add-MachinePath',
        'Update-PathFromRegistry',
        'Test-IsElevated'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()

    PrivateData = @{
        PSData = @{
            Tags         = @('Scoop', 'Winget', 'Chocolatey', 'PackageManagement', 'Install')
            LicenseUri   = 'https://github.com/MarkMichaelis/ScoopBucket/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/MarkMichaelis/ScoopBucket'
            ReleaseNotes = '0.3.0 — Default Scope=global across the schema; winget engine retries transient installer failures (Signal MSI ACCESS_VIOLATION, #75); Beyond Compare keeps the stock bcomp->BComp.exe shim and adds a separate bcompc shim for BComp.com; AIAgents + MicrosoftOffice365 migrated to declarative; Claude for Excel relocated to Office, Claude Desktop relocated to AIAgents; per-bundle hardcoded Pester tests collapsed to a single data-driven Bundles.Tests.ps1.'
        }
    }
}
