# Shared helpers for capturing, scrubbing, and applying a PowerToys settings
# snapshot. The pure helpers (path resolution, exclusion, scrubbing, write-set
# projection, secret guard) are deterministic so they can be unit-tested
# without a real PowerToys install. The process-control helpers are isolated
# behind thin functions so callers can mock them.
#
# Security note: PowerToys settings can carry secrets (MouseWithoutBorders
# SecurityKey + machine identity, Advanced Paste AI provider keys). The scrub
# helpers blank those values by property NAME so the snapshot is safe to commit
# to a public repo, while preserving everything the user actually wants to
# carry between machines (which modules are enabled, every keyboard shortcut /
# hotkey, FancyZones layouts, Keyboard Manager remaps).

function Get-PowerToysSettingsPath {
    <#
    .SYNOPSIS
        Resolve the live PowerToys settings folder.
    .DESCRIPTION
        Returns the explicit override when supplied, otherwise
        <LocalAppData>\Microsoft\PowerToys. Pure: the environment value is a
        parameter so the result is deterministic under test.
    .PARAMETER Override
        Explicit path to use instead of the default.
    .PARAMETER LocalAppData
        The %LOCALAPPDATA% root (defaulted from the environment).
    .OUTPUTS
        System.String -- the resolved settings folder path.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string]$Override,
        [string]$LocalAppData = $env:LOCALAPPDATA
    )
    if (-not [string]::IsNullOrWhiteSpace($Override)) { return $Override }
    return (Join-Path $LocalAppData 'Microsoft\PowerToys')
}

function Get-PowerToysSnapshotExclude {
    <#
    .SYNOPSIS
        Path-segment patterns whose files are volatile and never snapshotted.
    .DESCRIPTION
        Logs, telemetry, and update-state files are regenerated by PowerToys at
        runtime and carry no configuration, so excluding them keeps the snapshot
        small and free of churn. Matched (case-insensitively, with wildcards)
        against each segment of a setting's relative path.
    .OUTPUTS
        System.String[] -- the exclusion patterns.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param()
    return @(
        'Logs'
        'RunnerLogs'
        'etw'
        '*.log'
        'UpdateState.json'
        'last_version_run.json'
        'settings-telemetry.json'
    )
}

function Test-PowerToysPathExcluded {
    <#
    .SYNOPSIS
        Decide whether a relative settings path is volatile and should be skipped.
    .DESCRIPTION
        Returns $true when ANY segment of the relative path matches ANY exclude
        pattern (case-insensitive, wildcard). Pure.
    .PARAMETER RelativePath
        The candidate relative path (e.g. 'FancyZones\settings.json').
    .PARAMETER Exclude
        The exclusion patterns (see Get-PowerToysSnapshotExclude).
    .OUTPUTS
        System.Boolean.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory)][string]$RelativePath,
        [string[]]$Exclude = (Get-PowerToysSnapshotExclude)
    )
    $segments = $RelativePath -split '[\\/]+' | Where-Object { $_ -ne '' }
    foreach ($segment in $segments) {
        foreach ($pattern in $Exclude) {
            if ($segment -like $pattern) { return $true }
        }
    }
    return $false
}

function Get-PowerToysSecretPropertyName {
    <#
    .SYNOPSIS
        Property names whose values are secrets or machine identity and must be
        neutralized before a snapshot leaves the machine.
    .DESCRIPTION
        Matching is by EXACT property name (case-insensitive). Deliberately does
        NOT use a broad substring like '*key*' so that shortcut/hotkey fields
        (HotKeySwitchMachine, advanced-paste-ui-hotkey, Keyboard Manager remaps)
        are preserved -- those are exactly what the user wants to carry between
        machines.
    .OUTPUTS
        System.String[] -- the sensitive property names.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param()
    return @(
        'SecurityKey'
        'MachineID'
        'DeviceID'
        'Name2IP'
        'MachinePool'
        'MachineMatrixString'
        'ApiKey'
        'api_key'
        'access_token'
        'refresh_token'
        'client_secret'
        'ClientSecret'
        'secret'
        'password'
    )
}

function Get-PowerToysNeutralScalar {
    <#
    .SYNOPSIS
        The neutral replacement for a scalar/array value, matched to its shape.
    .DESCRIPTION
        Arrays become empty arrays, integers become 0, everything else becomes an
        empty string. Pure.
    .PARAMETER Original
        The original value being replaced.
    .OUTPUTS
        The neutral replacement value.
    #>
    [CmdletBinding()]
    param([AllowNull()][object]$Original)
    if ($Original -is [System.Collections.IEnumerable] -and $Original -isnot [string]) {
        return , @()
    }
    if ($Original -is [int] -or $Original -is [long] -or $Original -is [double]) {
        return 0
    }
    return ''
}

function Get-PowerToysNeutralizedValue {
    <#
    .SYNOPSIS
        Neutralize a secret property's value while preserving the PowerToys
        '{ "value": X }' wrapper shape.
    .DESCRIPTION
        PowerToys stores most settings as an object with a single 'value' member.
        When the secret property uses that wrapper, only the inner 'value' is
        blanked (so the structure PowerToys expects is preserved); otherwise the
        whole value is replaced with a same-shaped neutral. Pure.
    .PARAMETER Original
        The original (secret) property value.
    .OUTPUTS
        The neutralized value.
    #>
    [CmdletBinding()]
    param([AllowNull()][object]$Original)
    if (($Original -is [pscustomobject] -or $Original -is [System.Management.Automation.PSObject]) -and
        ($Original.PSObject.Properties.Name -contains 'value')) {
        $copy = [ordered]@{}
        foreach ($prop in $Original.PSObject.Properties) {
            if ($prop.Name -eq 'value') {
                $copy[$prop.Name] = Get-PowerToysNeutralScalar -Original $prop.Value
            } else {
                $copy[$prop.Name] = $prop.Value
            }
        }
        return [pscustomobject]$copy
    }
    return Get-PowerToysNeutralScalar -Original $Original
}

function Get-PowerToysSecretContent {
    <#
    .SYNOPSIS
        Extract the value that must be empty for a secret property to be clean.
    .DESCRIPTION
        Returns the inner 'value' member when the property uses the PowerToys
        wrapper, otherwise the value itself. Used by the residual-secret guard.
        Pure.
    .PARAMETER Value
        The secret property's value.
    .OUTPUTS
        The content to test for emptiness.
    #>
    [CmdletBinding()]
    param([AllowNull()][object]$Value)
    if (($Value -is [pscustomobject] -or $Value -is [System.Management.Automation.PSObject]) -and
        ($Value.PSObject.Properties.Name -contains 'value')) {
        return $Value.value
    }
    return $Value
}

function Get-PowerToysScrubbedObject {
    <#
    .SYNOPSIS
        Deep-copy a parsed settings object with all secret/identity property
        values neutralized.
    .DESCRIPTION
        Recurses through PSCustomObject nodes and arrays. Any property whose name
        is in Get-PowerToysSecretPropertyName has its value replaced by a neutral
        value of the same shape; all other values (including every shortcut /
        hotkey) are copied unchanged. Pure: returns a new object, mutates nothing.
    .PARAMETER InputObject
        The parsed settings object (from ConvertFrom-Json).
    .PARAMETER SecretName
        The sensitive property names to neutralize.
    .OUTPUTS
        The scrubbed object graph.
    #>
    [CmdletBinding()]
    param(
        [AllowNull()][object]$InputObject,
        [string[]]$SecretName = (Get-PowerToysSecretPropertyName)
    )
    if ($null -eq $InputObject) { return $null }

    if ($InputObject -is [string] -or $InputObject.GetType().IsPrimitive) {
        return $InputObject
    }

    if ($InputObject -is [System.Collections.IEnumerable] -and $InputObject -isnot [string]) {
        $list = foreach ($item in $InputObject) { Get-PowerToysScrubbedObject -InputObject $item -SecretName $SecretName }
        return , @($list)
    }

    if ($InputObject -is [pscustomobject] -or $InputObject -is [System.Management.Automation.PSObject]) {
        $copy = [ordered]@{}
        foreach ($prop in $InputObject.PSObject.Properties) {
            if ($SecretName -contains $prop.Name) {
                $copy[$prop.Name] = Get-PowerToysNeutralizedValue -Original $prop.Value
            } else {
                $copy[$prop.Name] = Get-PowerToysScrubbedObject -InputObject $prop.Value -SecretName $SecretName
            }
        }
        return [pscustomobject]$copy
    }

    return $InputObject
}

function Get-PowerToysSnapshotViolation {
    <#
    .SYNOPSIS
        Scan a snapshot object graph for residual secret values (defense in depth).
    .DESCRIPTION
        Walks the graph and reports any property whose name is sensitive yet still
        holds a non-empty / non-zero value. Export uses this as a hard gate so a
        secret can never be committed even if the scrubber misses a shape. Pure.
    .PARAMETER InputObject
        The (already scrubbed) object graph to verify.
    .PARAMETER SecretName
        The sensitive property names.
    .PARAMETER Path
        Internal: the dotted path accumulated during recursion.
    .OUTPUTS
        System.String[] -- one message per residual secret (empty when clean).
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param(
        [AllowNull()][object]$InputObject,
        [string[]]$SecretName = (Get-PowerToysSecretPropertyName),
        [string]$Path = ''
    )
    $violations = [System.Collections.Generic.List[string]]::new()
    if ($null -eq $InputObject) { return @() }

    if ($InputObject -is [System.Collections.IEnumerable] -and $InputObject -isnot [string]) {
        $i = 0
        foreach ($item in $InputObject) {
            $violations.AddRange([string[]]@(Get-PowerToysSnapshotViolation -InputObject $item -SecretName $SecretName -Path "$Path[$i]"))
            $i++
        }
        return $violations.ToArray()
    }

    if ($InputObject -is [pscustomobject] -or $InputObject -is [System.Management.Automation.PSObject]) {
        foreach ($prop in $InputObject.PSObject.Properties) {
            $childPath = if ($Path) { "$Path.$($prop.Name)" } else { $prop.Name }
            if ($SecretName -contains $prop.Name) {
                $val = Get-PowerToysSecretContent -Value $prop.Value
                $isEmpty = ($null -eq $val) -or ($val -is [string] -and $val -eq '') -or
                           (($val -is [int] -or $val -is [long] -or $val -is [double]) -and $val -eq 0) -or
                           ($val -is [System.Collections.IEnumerable] -and $val -isnot [string] -and @($val).Count -eq 0)
                if (-not $isEmpty) {
                    $violations.Add("Residual secret at '$childPath' (property '$($prop.Name)' is not neutralized).")
                }
            } else {
                $violations.AddRange([string[]]@(Get-PowerToysSnapshotViolation -InputObject $prop.Value -SecretName $SecretName -Path $childPath))
            }
        }
    }
    return $violations.ToArray()
}

function ConvertTo-PowerToysWriteSet {
    <#
    .SYNOPSIS
        Project a snapshot's files map into concrete (target path, JSON) pairs.
    .DESCRIPTION
        Validates each relative path (rejecting absolute or parent-escaping
        paths so a malicious snapshot cannot write outside SettingsRoot) and
        serializes each file's object to JSON. Pure.
    .PARAMETER Snapshot
        The snapshot object (must expose a 'files' map of relativePath -> object).
    .PARAMETER SettingsRoot
        The destination settings root the relative paths are joined onto.
    .PARAMETER Depth
        JSON serialization depth.
    .OUTPUTS
        PSCustomObject[] -- each with RelativePath, FullPath, Json.
    #>
    [CmdletBinding()]
    [OutputType([pscustomobject[]])]
    param(
        [Parameter(Mandatory)][object]$Snapshot,
        [Parameter(Mandatory)][string]$SettingsRoot,
        [int]$Depth = 25
    )
    $files = $Snapshot.files
    if ($null -eq $files) { return @() }

    $result = [System.Collections.Generic.List[pscustomobject]]::new()
    foreach ($prop in $files.PSObject.Properties) {
        $rel = $prop.Name
        if ([System.IO.Path]::IsPathRooted($rel) -or ($rel -split '[\\/]+') -contains '..') {
            throw "Refusing to write snapshot entry with unsafe path '$rel'."
        }
        $json = $prop.Value | ConvertTo-Json -Depth $Depth
        $result.Add([pscustomobject]@{
                RelativePath = $rel
                FullPath     = (Join-Path $SettingsRoot $rel)
                Json         = $json
            })
    }
    return $result.ToArray()
}

function Stop-PowerToysProcess {
    <#
    .SYNOPSIS
        Stop the PowerToys runner and its helper processes so settings can be
        replaced safely.
    .DESCRIPTION
        Terminates the runner ('PowerToys') AND every 'PowerToys.*' helper
        (Settings, FancyZones, MouseWithoutBorders, KeyboardManagerEngine, ...)
        by id (never by name) so an apply is not clobbered by the running app and
        so the helpers release the Global\PowerToys-<ver>-Default-1
        single-instance object before any restart. After issuing the stops it
        waits for the killed processes to exit, and warns if any survive (for
        example when PowerToys runs elevated and the kill is refused). No-op when
        PowerToys is not running.
    .OUTPUTS
        None.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param()
    $procs = Get-Process -Name 'PowerToys*' -ErrorAction SilentlyContinue |
        Where-Object { $_.ProcessName -like 'PowerToys*' }
    $killed = [System.Collections.Generic.List[int]]::new()
    foreach ($proc in $procs) {
        if ($PSCmdlet.ShouldProcess("PID $($proc.Id) ($($proc.ProcessName))", 'Stop PowerToys process')) {
            Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
            $killed.Add($proc.Id)
        }
    }
    if ($killed.Count -eq 0) { return }
    # Block until the killed processes exit so they release the Global
    # single-instance/IPC object before any restart collides with it.
    Wait-Process -Id $killed.ToArray() -Timeout 10 -ErrorAction SilentlyContinue
    # Re-query exactly the ids we tried to kill; any that remain were refused
    # (for example PowerToys running elevated while this session is not).
    $survivors = @(Get-Process -Id $killed.ToArray() -ErrorAction SilentlyContinue)
    if ($survivors.Count -gt 0) {
        Write-Warning ("PowerToys could not be fully stopped; {0} process(es) still running. Close PowerToys manually or run elevated, then retry." -f $survivors.Count)
    }
}

function Start-PowerToysProcess {
    <#
    .SYNOPSIS
        Relaunch PowerToys from a known install location, best-effort.
    .DESCRIPTION
        No-ops with a warning when any PowerToys process is still running so a
        second runner is never launched (a duplicate runner collides on the
        Global single-instance object and crashes with access-denied). Otherwise
        looks for PowerToys.exe under the per-user and machine install roots and
        starts the first match. Never throws -- restarting is a convenience.
    .OUTPUTS
        None.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param()
    $running = Get-Process -Name 'PowerToys*' -ErrorAction SilentlyContinue |
        Where-Object { $_.ProcessName -like 'PowerToys*' }
    if ($running) {
        Write-Warning 'PowerToys is already running; not launching a second instance.'
        return
    }
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'PowerToys\PowerToys.exe')
        (Join-Path $env:ProgramFiles 'PowerToys\PowerToys.exe')
    )
    $exe = $candidates | Where-Object { $_ -and (Test-Path -LiteralPath $_) } | Select-Object -First 1
    if (-not $exe) {
        Write-Verbose 'PowerToys.exe not found in the known install locations; not restarting.'
        return
    }
    if ($PSCmdlet.ShouldProcess($exe, 'Start PowerToys')) {
        Start-Process -FilePath $exe -ErrorAction SilentlyContinue
    }
}
