#
# Module manifest for the ScoopBucket helper module.
#
# Generated by hand (not via New-ModuleManifest) to keep the file small
# and readable. The companion .psm1 dot-sources Public/, Private/, and
# Classes/ in module scope; ScriptsToProcess also loads Classes\Package.ps1
# into the *caller* scope so bundle scripts can write `[Package]@{ ... }`
# after a plain Import-Module without `using module`.
#
@{
    RootModule        = 'MarkMichaelis.ScoopBucket.psm1'
    ModuleVersion     = '1.1.0'
    GUID              = 'b7e8a4c2-9f3d-4b76-8e6a-1c5d2f7b9e10'
    Author            = 'Mark Michaelis'
    CompanyName       = 'IntelliTect'
    Copyright         = '(c) Mark Michaelis. All rights reserved.'
    Description       = 'Declarative package manifests, install dispatcher, and tab-completion verification for the MarkMichaelis Scoop bucket. Provides the [Package] class, Invoke-PackageInstall, and the cross-bundle Install-Package / Get-Package helpers (which deliberately shadow the rarely-used PackageManagement cmdlets of the same name).'
    PowerShellVersion = '7.0'

    ScriptsToProcess  = @('Classes\Package.ps1')

    FormatsToProcess  = @('MarkMichaelis.ScoopBucket.format.ps1xml')

    FunctionsToExport = @(
        'Install-Package',
        'Uninstall-Package',
        'Get-Package',
        'Invoke-PackageInstall',
        'Invoke-PackageUninstall',
        'Update-PackageCompletion',
        'Import-PackageCompletion',
        'Add-MachinePath',
        'Update-PathFromRegistry',
        'Test-IsElevated',
        'Test-Command',
        'Test-ChocolateyPackageInstalled',
        'Test-ScoopPackageInstalled',
        'choco',
        'scoop',
        'Get-LocalBucket',
        'Get-InstallArgs',
        'Get-Program',
        'Install-WebDownload',
        'Install-WebDownloadOfZip',
        'Install-LocalManifest',
        'Install-BucketApp',
        'Register-CliCompletion',
        'Install-PSCompletionsModule',
        'Register-AllCliCompletions',
        'Invoke-CliCompletionsSweep',
        'Save-Artifact'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()

    PrivateData = @{
        PSData = @{
            Tags         = @('Scoop', 'Winget', 'Chocolatey', 'PackageManagement', 'Install')
            LicenseUri   = 'https://github.com/MarkMichaelis/ScoopBucket/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/MarkMichaelis/ScoopBucket'
            ReleaseNotes = '1.1.0 — Adds Save-Artifact for CI diagnostic producers. Persists rotating JSON snapshots under $env:TEMP\ScoopBucket\<Kind>\ with a stable latest.json; retains at most 5 newest stamped files per kind and prunes anything older than 1 day. Replaces the previous practice of writing cli-availability.json / test-results.json into the repo root. 1.0.0 — Module renamed from `ScoopBucket` to `MarkMichaelis.ScoopBucket` to namespace it against any future user-bucket modules and avoid collision with generic Scoop tooling. Public surface unchanged; bundle scripts now Import-Module MarkMichaelis.ScoopBucket. The console-waiting Beyond Compare shim is renamed from `bcompc` to `bcomp.com`.'
        }
    }
}
