#requires -Version 7.0
<#
.SYNOPSIS
    Back up and restore Microsoft PowerToys settings (enabled modules,
    keyboard shortcuts, FancyZones layouts, Keyboard Manager remaps, etc.)
    to and from a synced location.

.DESCRIPTION
    Reinstalling the bucket on a new machine reinstalls PowerToys but not its
    *settings*, which live in %LOCALAPPDATA%\Microsoft\PowerToys (a general
    settings.json that records which modules are enabled, plus a per-module
    settings.json for each utility). This script mirrors that folder to a
    synced backup location so the configuration survives a fresh install and
    travels between machines.

    The backup destination defaults to a folder under the user's OneDrive
    ($env:OneDrive\Backups\PowerToys), falling back to the user profile when
    OneDrive is not configured. The settings are deliberately copied to the
    user's private synced storage rather than committed to this PUBLIC bucket
    repo, because PowerToys settings contain secrets (Mouse Without Borders
    stores a security key and machine names; Advanced Paste can hold an AI
    API key).

    Running the script with no switches -- including the `scoop install`
    installer action -- performs a BACKUP (mirror live settings -> backup
    root). Pass -Restore to mirror a backup back into the live settings
    folder; PowerToys is stopped first and restarted afterwards.

    All decision helpers are pure (path resolution, exclusion filtering) so
    they are unit-testable without touching a real PowerToys install. The
    imperative copy / process control is isolated behind thin functions that
    honour -WhatIf.

.PARAMETER Restore
    Restore a backup into the live settings folder instead of backing up.

.PARAMETER SettingsRoot
    Override the live PowerToys settings folder (defaults to
    %LOCALAPPDATA%\Microsoft\PowerToys).

.PARAMETER BackupRoot
    Override the backup destination (defaults to a OneDrive-synced folder).

.PARAMETER NoRestart
    On -Restore, do not relaunch PowerToys after the settings are restored.

.EXAMPLE
    .\PowerToysSettingsBackup.ps1
    Backs up the current PowerToys settings to the default synced location.

.EXAMPLE
    .\PowerToysSettingsBackup.ps1 -Restore
    Stops PowerToys, restores settings from the default backup, restarts it.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [switch]$Restore,
    [string]$SettingsRoot,
    [string]$BackupRoot,
    [switch]$NoRestart
)

$ErrorActionPreference = 'Stop'

function Get-PowerToysSettingsRoot {
    <#
    .SYNOPSIS
        Resolve the live PowerToys settings folder.
    .DESCRIPTION
        Returns the explicit override when supplied, otherwise
        <LocalAppData>\Microsoft\PowerToys. Pure: takes the environment value
        as a parameter so it is deterministic under test.
    .PARAMETER Override
        Explicit path to use instead of the default.
    .PARAMETER LocalAppData
        The %LOCALAPPDATA% root (defaulted from the environment).
    .OUTPUTS
        System.String -- the resolved settings folder path.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string]$Override,
        [string]$LocalAppData = $env:LOCALAPPDATA
    )
    if (-not [string]::IsNullOrWhiteSpace($Override)) { return $Override }
    return (Join-Path $LocalAppData 'Microsoft\PowerToys')
}

function Resolve-PowerToysBackupRoot {
    <#
    .SYNOPSIS
        Resolve the backup destination folder.
    .DESCRIPTION
        Returns the explicit override when supplied; otherwise a folder under
        the user's OneDrive (so the backup syncs across machines and stays out
        of the public bucket repo); otherwise a folder under the user profile
        when OneDrive is not configured. Pure: all inputs are parameters.
    .PARAMETER Override
        Explicit destination to use instead of the default.
    .PARAMETER OneDrive
        The %OneDrive% root (defaulted from the environment).
    .PARAMETER UserProfile
        The %USERPROFILE% root used for the non-OneDrive fallback.
    .OUTPUTS
        System.String -- the resolved backup root path.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string]$Override,
        [string]$OneDrive = $env:OneDrive,
        [string]$UserProfile = $env:USERPROFILE
    )
    if (-not [string]::IsNullOrWhiteSpace($Override)) { return $Override }
    if (-not [string]::IsNullOrWhiteSpace($OneDrive)) {
        return (Join-Path $OneDrive 'Backups\PowerToys')
    }
    return (Join-Path $UserProfile 'PowerToys-SettingsBackup')
}

function Get-PowerToysBackupExclude {
    <#
    .SYNOPSIS
        The default set of volatile path-segment patterns to skip in a backup.
    .DESCRIPTION
        These are regenerated by PowerToys at runtime and carry no
        configuration, so excluding them keeps the backup small and free of
        churn. Matched (case-insensitively, with wildcards) against each
        segment of a setting's relative path.
    .OUTPUTS
        System.String[] -- the exclusion patterns.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param()
    return @(
        'Logs'
        'etw'
        '*.log'
        'UpdateState.json'
        'last_version_run.json'
    )
}

function Select-PowerToysBackupRelativePath {
    <#
    .SYNOPSIS
        Filter a list of relative setting paths down to the ones worth backing up.
    .DESCRIPTION
        A relative path is dropped when ANY of its segments matches ANY exclude
        pattern (case-insensitive, wildcard). Pure: returns the kept subset in
        input order, writes nothing.
    .PARAMETER RelativePath
        The candidate relative paths (e.g. 'settings.json',
        'FancyZones\settings.json', 'Logs\app.log').
    .PARAMETER Exclude
        The exclusion patterns (see Get-PowerToysBackupExclude).
    .OUTPUTS
        System.String[] -- the relative paths to copy.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param(
        [string[]]$RelativePath,
        [string[]]$Exclude = (Get-PowerToysBackupExclude)
    )
    $kept = foreach ($path in $RelativePath) {
        if ([string]::IsNullOrWhiteSpace($path)) { continue }
        $segments = $path -split '[\\/]+' | Where-Object { $_ -ne '' }
        $isExcluded = $false
        foreach ($segment in $segments) {
            foreach ($pattern in $Exclude) {
                if ($segment -like $pattern) { $isExcluded = $true; break }
            }
            if ($isExcluded) { break }
        }
        if (-not $isExcluded) { $path }
    }
    return [string[]]$kept
}

function Stop-PowerToysProcess {
    <#
    .SYNOPSIS
        Stop the PowerToys runner and its helper processes so settings can be
        replaced safely.
    .DESCRIPTION
        Terminates the runner ('PowerToys') AND every 'PowerToys.*' helper
        (Settings, FancyZones, MouseWithoutBorders, KeyboardManagerEngine, ...)
        by id (never by name) so a settings restore is not clobbered by the
        running app and so the helpers release the
        Global\PowerToys-<ver>-Default-1 single-instance object before any
        restart. After issuing the stops it waits for the killed processes to
        exit, and warns if any survive (for example when PowerToys runs elevated
        and the kill is refused). No-op when PowerToys is not running.
    .OUTPUTS
        None.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param()
    $procs = Get-Process -Name 'PowerToys*' -ErrorAction SilentlyContinue |
        Where-Object { $_.ProcessName -like 'PowerToys*' }
    $killed = [System.Collections.Generic.List[int]]::new()
    foreach ($proc in $procs) {
        if ($PSCmdlet.ShouldProcess("PID $($proc.Id) ($($proc.ProcessName))", 'Stop PowerToys process')) {
            Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
            $killed.Add($proc.Id)
        }
    }
    if ($killed.Count -eq 0) { return }
    # Block until the killed processes exit so they release the Global
    # single-instance/IPC object before any restart collides with it.
    Wait-Process -Id $killed.ToArray() -Timeout 10 -ErrorAction SilentlyContinue
    # Re-query exactly the ids we tried to kill; any that remain were refused
    # (for example PowerToys running elevated while this session is not).
    $survivors = @(Get-Process -Id $killed.ToArray() -ErrorAction SilentlyContinue)
    if ($survivors.Count -gt 0) {
        Write-Warning ("PowerToys could not be fully stopped; {0} process(es) still running. Close PowerToys manually or run elevated, then retry." -f $survivors.Count)
    }
}

function Start-PowerToysProcess {
    <#
    .SYNOPSIS
        Relaunch PowerToys from a known install location, best-effort.
    .DESCRIPTION
        No-ops with a warning when any PowerToys process is still running so a
        second runner is never launched (a duplicate runner collides on the
        Global single-instance object and crashes with access-denied). Otherwise
        looks for PowerToys.exe under the per-user and machine install roots
        and starts the first match. Never throws -- restarting is a
        convenience, not a guarantee.
    .OUTPUTS
        None.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param()
    $running = Get-Process -Name 'PowerToys*' -ErrorAction SilentlyContinue |
        Where-Object { $_.ProcessName -like 'PowerToys*' }
    if ($running) {
        Write-Warning 'PowerToys is already running; not launching a second instance.'
        return
    }
    $candidates = @(
        (Join-Path $env:LOCALAPPDATA 'PowerToys\PowerToys.exe')
        (Join-Path $env:ProgramFiles 'PowerToys\PowerToys.exe')
    )
    $exe = $candidates | Where-Object { $_ -and (Test-Path -LiteralPath $_) } | Select-Object -First 1
    if (-not $exe) {
        Write-Verbose 'PowerToys.exe not found in the known install locations; not restarting.'
        return
    }
    if ($PSCmdlet.ShouldProcess($exe, 'Start PowerToys')) {
        Start-Process -FilePath $exe -ErrorAction SilentlyContinue
    }
}

function Backup-PowerToysSettings {
    <#
    .SYNOPSIS
        Mirror the live PowerToys settings folder to the backup root.
    .DESCRIPTION
        Copies every setting file under SettingsRoot (minus the volatile
        excludes) to the same relative location under BackupRoot, creating
        destination directories as needed. Returns a summary object. Honours
        -WhatIf.
    .PARAMETER SettingsRoot
        The live settings folder to read from.
    .PARAMETER BackupRoot
        The destination folder to write the mirror to.
    .PARAMETER Exclude
        Volatile path-segment patterns to skip (see Get-PowerToysBackupExclude).
    .OUTPUTS
        PSCustomObject -- SettingsRoot, BackupRoot, FileCount, Files.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([pscustomobject])]
    param(
        [string]$SettingsRoot = (Get-PowerToysSettingsRoot),
        [string]$BackupRoot = (Resolve-PowerToysBackupRoot),
        [string[]]$Exclude = (Get-PowerToysBackupExclude)
    )
    if (-not (Test-Path -LiteralPath $SettingsRoot -PathType Container)) {
        throw "PowerToys settings folder not found: $SettingsRoot"
    }
    $files = Get-ChildItem -LiteralPath $SettingsRoot -Recurse -File -ErrorAction SilentlyContinue
    $relative = foreach ($file in $files) {
        $file.FullName.Substring($SettingsRoot.Length).TrimStart('\', '/')
    }
    $keep = Select-PowerToysBackupRelativePath -RelativePath $relative -Exclude $Exclude
    $copied = [System.Collections.Generic.List[string]]::new()
    foreach ($rel in $keep) {
        $source = Join-Path $SettingsRoot $rel
        $destination = Join-Path $BackupRoot $rel
        if ($PSCmdlet.ShouldProcess($destination, 'Copy PowerToys setting')) {
            $destinationDir = Split-Path -Parent $destination
            if (-not (Test-Path -LiteralPath $destinationDir)) {
                New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
            }
            Copy-Item -LiteralPath $source -Destination $destination -Force
            $copied.Add($rel)
        }
    }
    return [pscustomobject]@{
        SettingsRoot = $SettingsRoot
        BackupRoot   = $BackupRoot
        FileCount    = $copied.Count
        Files        = $copied.ToArray()
    }
}

function Restore-PowerToysSettings {
    <#
    .SYNOPSIS
        Mirror a PowerToys settings backup back into the live settings folder.
    .DESCRIPTION
        Stops PowerToys, copies every file under BackupRoot to the same
        relative location under SettingsRoot, then (unless -NoRestart)
        relaunches PowerToys. Returns a summary object. Honours -WhatIf.
    .PARAMETER BackupRoot
        The backup folder to read from.
    .PARAMETER SettingsRoot
        The live settings folder to write to.
    .PARAMETER NoRestart
        Do not relaunch PowerToys after restoring.
    .OUTPUTS
        PSCustomObject -- SettingsRoot, BackupRoot, FileCount, Files.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([pscustomobject])]
    param(
        [string]$BackupRoot = (Resolve-PowerToysBackupRoot),
        [string]$SettingsRoot = (Get-PowerToysSettingsRoot),
        [switch]$NoRestart
    )
    if (-not (Test-Path -LiteralPath $BackupRoot -PathType Container)) {
        throw "No PowerToys backup found at: $BackupRoot"
    }
    Stop-PowerToysProcess
    $files = Get-ChildItem -LiteralPath $BackupRoot -Recurse -File -ErrorAction SilentlyContinue
    $restored = [System.Collections.Generic.List[string]]::new()
    foreach ($file in $files) {
        $rel = $file.FullName.Substring($BackupRoot.Length).TrimStart('\', '/')
        $destination = Join-Path $SettingsRoot $rel
        if ($PSCmdlet.ShouldProcess($destination, 'Restore PowerToys setting')) {
            $destinationDir = Split-Path -Parent $destination
            if (-not (Test-Path -LiteralPath $destinationDir)) {
                New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
            }
            Copy-Item -LiteralPath $file.FullName -Destination $destination -Force
            $restored.Add($rel)
        }
    }
    if (-not $NoRestart) { Start-PowerToysProcess }
    return [pscustomobject]@{
        SettingsRoot = $SettingsRoot
        BackupRoot   = $BackupRoot
        FileCount    = $restored.Count
        Files        = $restored.ToArray()
    }
}

# Main orchestration: runs only when invoked (not when dot-sourced by tests,
# where $MyInvocation.InvocationName is '.'). The default action -- including
# the `scoop install` installer -- is a backup.
if ($MyInvocation.InvocationName -ne '.') {
    $resolvedSettings = Get-PowerToysSettingsRoot -Override $SettingsRoot
    $resolvedBackup = Resolve-PowerToysBackupRoot -Override $BackupRoot

    if ($Restore) {
        Write-Host "Restoring PowerToys settings from $resolvedBackup ..."
        $result = Restore-PowerToysSettings -BackupRoot $resolvedBackup -SettingsRoot $resolvedSettings -NoRestart:$NoRestart
        Write-Host "Restored $($result.FileCount) setting file(s) to $($result.SettingsRoot)."
    } else {
        Write-Host "Backing up PowerToys settings to $resolvedBackup ..."
        $result = Backup-PowerToysSettings -SettingsRoot $resolvedSettings -BackupRoot $resolvedBackup
        Write-Host "Backed up $($result.FileCount) setting file(s) to $($result.BackupRoot)."
    }
}
